### PR TITLE
feat: Upgrade to Angular 18 (#417 #418)

### LINKED ISSUE #417: Angular 18 Support
We'd like to upgrade to Angular 18, but there is a peer dependency of ngx-mapbox-gl, which doesn't allow that. can this peer dependency be changed?

### PR DESCRIPTION
**Pull request by luigi-iss**
- Upgrade to Angular 18
- Upgraded some of the dependencies packages
- Upgraded CI to use v0.15 version of nrwl workflows
- Fixes #417 and #418

### CODE REVIEW

**Comment by datzgit** [comment]
Can someone approve this asap please?  I bet there are many who need to install the module also on Angular v18. 
Much appreciated!

**Comment by luigi-iss** [comment]
@Wykks anything we can do to help you with this and general up keep of the package/repo? Just let me know. Thanks

**Comment by BaatenHannes** [comment]
Would be great if it could be completed! Thanks

**Comment by Wykks** [comment]
Hello!

Sorry for the big delay, thanks for the update!

**Comment by luigi-iss** [comment]
@Wykks thanks for actioning this and sorry for missing to update of the peerDependencies! take care

**Pull request merged**
