### PR TITLE
Update all dependencies to their latest versions. Angular => 8.0.0, mapbox-gl-js => 1.0.0

### PR DESCRIPTION
**Pull request by dmytro-gokun**
+ rest of the dependencies

### CODE REVIEW

**Comment by dmytro-gokun** [comment]
@Wykks Looks like Angular 8 requires newer node. Can we change that for CI? 
We are getting this message:  Expected version ">= 10.9.0".

**Comment by dmytro-gokun** [comment]
@Wykks I've updated .travis.yml to use the proper node version. 
Please let me know what you think of this PR. Was it a good idea at all to do this all-at-once update?

**Comment by Wykks** [comment]
Will take a look this week-end (hopefully), but yep, looks good 👍 

After that, we're gonna need to read through mapbox-gl changelog to support new stuff.
(Maybe this week-end too).

**Comment by dmytro-gokun** [comment]
@Wykks as far as I understand, this release does not have anything new codewise. It's all about their change in pricing model: https://blog.mapbox.com/new-pricing-46b7c26166e7 So, you need to make it clear in release notes for ngx-mapbox-gl as well. Maybe, some folks would like to stay on the old pricing model. However, I was not able to find any info on how long they plan to support it (the old pricing model). In any case, they're not likely to produce any updates to that old branch 0.XX, so 1.0.0 is a way to go, anyway

**Comment by Wykks** [comment]
Between v0.54.0 and v1.0.0 yes. But ngx-mapbox-gl was at 0.53.1.
v0.54.0 add some stuff (like this https://github.com/Wykks/ngx-mapbox-gl/issues/148).

Maybe it's better to add v0.54.0 support in the v3.x version of ngx-mapbox-gl (despite the minor breaking changes in mapbox-gl).
Then align v4 with mapbox-gl 1.0

**Comment by dmytro-gokun** [comment]
@Wykks yeah, i think you are right (Y) Let me know if you need help with some particular issues. I cannot promise to do lot, but i can carve out 2-3 hrs a week to work on this library. Our app will benefit from it :)

**Comment by Wykks** [comment]
@dmytro-gokun If you can take a look at this issue, it would be great then :smile: 
https://github.com/Wykks/ngx-mapbox-gl/issues/139#issuecomment-500066768
I believe this should be part of the v4 release.

**Comment by dmytro-gokun** [comment]
@Wykks sure, please assign that to me and will try to have a look at it over the next week or two. not sure if right now i clearly understand the issue, but i will dive into it and ask appropriate questions, if any.

As to this PR, i believe we may close it as it's now been decided to have separate releases for different Angular 8 & mapbox-gl-js update. So it's not relevant anymore.

**Comment by Wykks** [comment]
Cool!
After one last V3 release, I think I'll merge this into master for V4. It's still relevant :)

**Pull request closed without merging**
