### PR TITLE
Update/angular 13

### PR DESCRIPTION
**Pull request by eschricker**
I have updated the angular dependency to version 13 and replaced tslint with eslint.

### CODE REVIEW

**Comment by Wykks** [comment]
Hi! Thanks the PR, I'll take a look this weekend!

**Comment by Wykks** [comment]
Looks good enough to me. Not sure why you removed the yarn.lock. Thanks :)

**Comment by Wykks** [comment]
Actually I'll have to revert this, it doesn't build :/

**Comment by Seryal85** [comment]
Which is error with build, something unusual?

**Pull request merged**
