### PR TITLE
Fix control order when using custom controls alongside built-in controls (#75)

### PR DESCRIPTION
**Pull request by dmytro-gokun**
@Wykks When (if) this is merged in, can you plz make a minor release? I want to use this fix in production :) Thanks

### CODE REVIEW

**Comment by Wykks** [comment]
Interesting way of fixing this issue.

I currently don't have the exact life-cycle rule (too easy to forgot...) that make this reliable, but I trust you :D

**Comment by Wykks** [comment]
Will backport to 3.x branch for a release.

**Comment by Wykks** [comment]
Released as 3.3.1

**Comment by dmytro-gokun** [comment]
Thanks a lot (Y)

**Pull request merged**
