### PR TITLE
fix(map): add an additional setStyle() call to prevent map loading issues...

### PR DESCRIPTION
**Pull request by sroettering**
…on IE11 (see https://github.com/mapbox/mapbox-gl-js/issues/4821#issuecomment-358998674).
Main issue is here: https://github.com/mapbox/mapbox-gl-js/issues/4623
Fixes https://github.com/Wykks/ngx-mapbox-gl/issues/66

### CODE REVIEW

**Comment by sroettering** [comment]
Sadly mapbox logs an error, if we do a `setStyle()` directly after creating the map.
Is there any way around this?

**Comment by sroettering** [comment]
No I closed it because I was not able to fix the e2e test. The e2e tests check the log output and mapbox throws an (IMO unnecessary) error that I can not prevent :-/ Maybe you have an idea for the e2e tests?

**Comment by Wykks** [comment]
e2e tests only run on chrome, so it's fine if we add a check for IE11

**Comment by sroettering** [comment]
ah I see. I will include an IE check then!

**Pull request merged**
